/**
 * Comprehensive Cyber Threat & Scam Lexicon Repository for India.
 * Contains structured threat keywords, vernacular phrases, 
 * regional dialect variations, and leetspeak variants.
 */
const SEED_SCAM_WORDS = [
  // 1. Task & Part-Time Job Scams
  { word: 'ghar baithe', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.95 },
  { word: 'ghar baithe kamaye', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.98 },
  { word: 'daily kamana', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.92 },
  { word: 'daily kamayein', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.92 },
  { word: 'youtube video like', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.95 },
  { word: 'like karo aur screenshot bhejo', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.99 },
  { word: 'screenshot bhejo', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.88 },
  { word: 'part-time job', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.85 },
  { word: 'full-time job', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.75 },
  { word: 'zero investment', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.92 },
  { word: 'investment zero', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.92 },
  { word: 'work from home', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.82 },
  { word: 'telegram task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.95 },
  { word: 'telegram vip group', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.96 },
  { word: 'vip manager', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.90 },
  { word: 'commission payout', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.88 },
  { word: 'prepaid task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.95 },
  { word: 'earning app', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.85 },
  { word: 'daily payout', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.88 },
  { word: 'data entry work', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.80 },
  { word: 'hotel review task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.94 },
  { word: 'google map review job', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.96 },
  { word: 'movie rating task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.95 },
  { word: 'instagram follow task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.94 },
  { word: 'per day earning', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.88 },
  { word: 'daily 3000-5000', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.95 },
  { word: 'whatsapp par message karein', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.88 },
  { word: 'wa.me', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.82 },
  { word: 't.me', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.82 },
  { word: 'daily passive income', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.90 },
  { word: 'recharge task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.92 },
  { word: 'bonus task', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.88 },
  { word: 'earn from mobile', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.85 },
  { word: 'online kamai', category: 'TASK_JOB_FRAUD', language: 'Hinglish', severity: 0.90 },
  { word: 'easy income', category: 'TASK_JOB_FRAUD', language: 'English', severity: 0.85 },

  // 2. Bank Account Suspension & Netbanking
  { word: 'khata bandh', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.95 },
  { word: 'account block', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.95 },
  { word: 'y0ur sb1', category: 'BANK_BLOCK', language: 'Leetspeak', severity: 0.99 },
  { word: 'yono blocked', category: 'BANK_BLOCK', language: 'English', severity: 0.98 },
  { word: 'yono access disabled', category: 'BANK_BLOCK', language: 'English', severity: 0.98 },
  { word: 'netbanking suspended', category: 'BANK_BLOCK', language: 'English', severity: 0.96 },
  { word: 'debit card blocked', category: 'BANK_BLOCK', language: 'English', severity: 0.94 },
  { word: 'atm card block', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.94 },
  { word: 'khata block ho jayega', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.99 },
  { word: 'bank account freeze', category: 'BANK_BLOCK', language: 'English', severity: 0.96 },
  { word: 'rok diya gaya', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.92 },
  { word: 'suspend kar diya', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.95 },
  { word: 'sbi netbanking', category: 'BANK_BLOCK', language: 'English', severity: 0.70 },
  { word: 'hdfc bank alert', category: 'BANK_BLOCK', language: 'English', severity: 0.70 },
  { word: 'icici direct notice', category: 'BANK_BLOCK', language: 'English', severity: 0.70 },
  { word: 'pnb khata', category: 'BANK_BLOCK', language: 'Hinglish', severity: 0.75 },
  { word: 'bob yono', category: 'BANK_BLOCK', language: 'English', severity: 0.85 },
  { word: 'kotak 811 block', category: 'BANK_BLOCK', language: 'English', severity: 0.92 },
  { word: 'axis bank hold', category: 'BANK_BLOCK', language: 'English', severity: 0.90 },
  { word: 'unverified account', category: 'BANK_BLOCK', language: 'English', severity: 0.85 },
  { word: 'transaction hold', category: 'BANK_BLOCK', language: 'English', severity: 0.90 },
  { word: 'account deactivated', category: 'BANK_BLOCK', language: 'English', severity: 0.95 },
  { word: 'credit card limit block', category: 'BANK_BLOCK', language: 'English', severity: 0.92 },
  { word: 'reward points expire', category: 'BANK_BLOCK', language: 'English', severity: 0.88 },
  { word: 'redeem bank reward', category: 'BANK_BLOCK', language: 'English', severity: 0.88 },
  { word: 'blck', category: 'BANK_BLOCK', language: 'Leetspeak', severity: 0.95 },
  { word: 'b4nd', category: 'BANK_BLOCK', language: 'Leetspeak', severity: 0.95 },
  { word: 'bl0cked', category: 'BANK_BLOCK', language: 'Leetspeak', severity: 0.95 },

  // 3. Digital Arrest & Legal Extortion
  { word: 'digital arrest', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },
  { word: 'cbi warrant', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },
  { word: 'mumbai police crime branch', category: 'DIGITAL_ARREST', language: 'English', severity: 0.98 },
  { word: 'cyber cell delhi', category: 'DIGITAL_ARREST', language: 'English', severity: 0.96 },
  { word: 'drugs in parcel', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },
  { word: 'narcotics department seizure', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },
  { word: 'customs detention notice', category: 'DIGITAL_ARREST', language: 'English', severity: 0.98 },
  { word: 'money laundering investigation', category: 'DIGITAL_ARREST', language: 'English', severity: 0.96 },
  { word: 'ed officer summons', category: 'DIGITAL_ARREST', language: 'English', severity: 0.98 },
  { word: 'skype video verification', category: 'DIGITAL_ARREST', language: 'English', severity: 0.99 },
  { word: 'court arrest warrant', category: 'DIGITAL_ARREST', language: 'English', severity: 0.99 },
  { word: 'passport seized', category: 'DIGITAL_ARREST', language: 'English', severity: 0.98 },
  { word: 'illegal consignment', category: 'DIGITAL_ARREST', language: 'English', severity: 0.98 },
  { word: 'mdma parcel', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },
  { word: 'trai official notice', category: 'DIGITAL_ARREST', language: 'English', severity: 0.95 },
  { word: 'supreme court notice', category: 'DIGITAL_ARREST', language: 'English', severity: 0.95 },
  { word: 'police station report', category: 'DIGITAL_ARREST', language: 'English', severity: 0.90 },
  { word: 'non-bailable warrant', category: 'DIGITAL_ARREST', language: 'English', severity: 0.99 },
  { word: 'immediate surveillance', category: 'DIGITAL_ARREST', language: 'English', severity: 0.92 },
  { word: 'room digital arrest', category: 'DIGITAL_ARREST', language: 'English', severity: 1.0 },

  // 4. Traffic e-Challan & Fake APK
  { word: 'traffic challan', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.90 },
  { word: 'echallan pending', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.94 },
  { word: 'mparivahan apk', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.99 },
  { word: 'parivahan-sewa.apk', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 1.0 },
  { word: 'court fine pending', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.92 },
  { word: 'vehicle impound notice', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.95 },
  { word: 'driving licence cancelled', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.95 },
  { word: 'lok adalat notice', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.90 },
  { word: 'challan pay immediately', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.94 },
  { word: 'rto penalty fine', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.90 },
  { word: 'traffic court warrant', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.96 },
  { word: 'rc book suspended', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.92 },
  { word: 'delhi traffic police fine', category: 'TRAFFIC_ECHALLAN', language: 'English', severity: 0.90 },

  // 5. India Post & Parcel Delivery Scams
  { word: 'india post delivery failed', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.96 },
  { word: 'incorrect address parcel', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.95 },
  { word: 'update delivery address', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.94 },
  { word: 'package returned to hub', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.92 },
  { word: 'speed post detained', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.95 },
  { word: 'redelivery fee rs 5', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.98 },
  { word: 'customs duty parcel', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.92 },
  { word: 'reschedule your parcel', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.94 },
  { word: 'consignment held at sorting office', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.95 },
  { word: 'blue dart delivery incomplete', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.90 },
  { word: 'delhivery package pending', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.90 },
  { word: 'indiapost-track.xyz', category: 'PARCEL_DELIVERY', language: 'English', severity: 0.99 },

  // 6. Electricity & Bijli Power Cut
  { word: 'bijli connection cut', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.98 },
  { word: 'aaj raat 9 baje bijli bandh', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.99 },
  { word: 'power disconnect tonight', category: 'UTILITY_BILL', language: 'English', severity: 0.98 },
  { word: 'ebill overdue', category: 'UTILITY_BILL', language: 'English', severity: 0.92 },
  { word: 'electricity officer call', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.96 },
  { word: 'meter connection terminate', category: 'UTILITY_BILL', language: 'English', severity: 0.95 },
  { word: 'light bill jama karein', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.92 },
  { word: 'bijli kaat di jayegi', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.99 },
  { word: 'substation line disconnect', category: 'UTILITY_BILL', language: 'Hinglish', severity: 0.95 },
  { word: 'unpaid bill helpline', category: 'UTILITY_BILL', language: 'English', severity: 0.88 },
  { word: 'bses power bill fine', category: 'UTILITY_BILL', language: 'English', severity: 0.90 },
  { word: 'tneb electricity cut', category: 'UTILITY_BILL', language: 'English', severity: 0.92 },
  { word: 'mseb power alert', category: 'UTILITY_BILL', language: 'English', severity: 0.92 },

  // 7. KYC, PAN & Aadhaar Fraud
  { word: 'pan aadhaar link penalty', category: 'KYC_FRAUD', language: 'English', severity: 0.98 },
  { word: 'pan card inoperative', category: 'KYC_FRAUD', language: 'English', severity: 0.96 },
  { word: 'penalty rs 10000', category: 'KYC_FRAUD', language: 'English', severity: 0.92 },
  { word: 'k-y-c update immediate', category: 'KYC_FRAUD', language: 'Leetspeak', severity: 0.98 },
  { word: 're-kyc verification', category: 'KYC_FRAUD', language: 'English', severity: 0.94 },
  { word: 'biometric update pending', category: 'KYC_FRAUD', language: 'English', severity: 0.92 },
  { word: 'aadhaar suspended', category: 'KYC_FRAUD', language: 'English', severity: 0.95 },
  { word: 'kyc expired today', category: 'KYC_FRAUD', language: 'English', severity: 0.96 },
  { word: 'pancard block', category: 'KYC_FRAUD', language: 'Hinglish', severity: 0.95 },
  { word: 'kyc document upload', category: 'KYC_FRAUD', language: 'English', severity: 0.90 },
  { word: 'link your pan here', category: 'KYC_FRAUD', language: 'English', severity: 0.95 },
  { word: 're-verification deadline', category: 'KYC_FRAUD', language: 'English', severity: 0.92 },
  { word: 'updte kyc', category: 'KYC_FRAUD', language: 'Leetspeak', severity: 0.95 },

  // 8. OTP, Credentials & Remote Access
  { word: 'otp batayein', category: 'OTP_CREDENTIALS', language: 'Hinglish', severity: 0.99 },
  { word: '0tpp', category: 'OTP_CREDENTIALS', language: 'Leetspeak', severity: 0.98 },
  { word: 'share your otp', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.99 },
  { word: 'mpin share karein', category: 'OTP_CREDENTIALS', language: 'Hinglish', severity: 0.99 },
  { word: 'cvv bataye', category: 'OTP_CREDENTIALS', language: 'Hinglish', severity: 0.99 },
  { word: 'anydesk download', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.99 },
  { word: 'teamviewer quicksupport', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.99 },
  { word: 'rustdesk screen share', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.99 },
  { word: 'install support apk', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.98 },
  { word: 'tpin enter karein', category: 'OTP_CREDENTIALS', language: 'Hinglish', severity: 0.98 },
  { word: 'remote verification tool', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.95 },
  { word: 'screen sharing code', category: 'OTP_CREDENTIALS', language: 'English', severity: 0.98 },

  // 9. Fake Lottery, Rewards & KBC
  { word: 'badhai ho', category: 'LOTTERY_CASHBACK', language: 'Hinglish', severity: 0.88 },
  { word: 'kbc lottery winner', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.99 },
  { word: '25 lakh inam nikla', category: 'LOTTERY_CASHBACK', language: 'Hinglish', severity: 0.99 },
  { word: 'cashback rs 50000', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.95 },
  { word: 'jio lucky draw winner', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.98 },
  { word: 'claim prize deposit fee', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.99 },
  { word: 'tata motors prize winner', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.98 },
  { word: 'spin wheel reward won', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.94 },
  { word: 'gpay cashback claim link', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.95 },
  { word: 'phonepe scratch card won', category: 'LOTTERY_CASHBACK', language: 'English', severity: 0.95 },

  // 10. Fake Instant Loan Apps & Extortion
  { word: 'loan without cibil', category: 'FAKE_LOAN', language: 'English', severity: 0.92 },
  { word: '5 lakh pre-approved instant loan', category: 'FAKE_LOAN', language: 'English', severity: 0.94 },
  { word: 'zero interest loan app', category: 'FAKE_LOAN', language: 'English', severity: 0.92 },
  { word: 'loan overdue contact harassment', category: 'FAKE_LOAN', language: 'English', severity: 0.98 },
  { word: 'contact list broadcast debt', category: 'FAKE_LOAN', language: 'English', severity: 0.99 },
  { word: '7 day loan app', category: 'FAKE_LOAN', language: 'English', severity: 0.98 },
  { word: 'disbursal within 2 minutes', category: 'FAKE_LOAN', language: 'English', severity: 0.90 },
  { word: 'pan instant loan apk', category: 'FAKE_LOAN', language: 'English', severity: 0.95 },

  // 11. SIM 5G & Telecom Deactivation
  { word: 'sim block tonight', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.95 },
  { word: '4g to 5g free upgrade sim', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.95 },
  { word: 'trai sim disconnection', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.98 },
  { word: 'sim swap verification', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.96 },
  { word: 'esim activation qr', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.96 },
  { word: 'porting code sms', category: 'SIM_5G_FRAUD', language: 'English', severity: 0.92 },

  // 12. Income Tax & Government Schemes
  { word: 'income tax refund approved', category: 'INCOME_TAX', language: 'English', severity: 0.98 },
  { word: 'tds credit claim portal', category: 'INCOME_TAX', language: 'English', severity: 0.96 },
  { word: 'itr refund bank account update', category: 'INCOME_TAX', language: 'English', severity: 0.98 },
  { word: 'epfo pf account freeze', category: 'INCOME_TAX', language: 'English', severity: 0.95 },
  { word: 'pension kyc update', category: 'INCOME_TAX', language: 'English', severity: 0.92 },
  { word: 'pm kisan yojana rs 2000 credit', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.95 },
  { word: 'ladki bahin yojana kyc update', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.95 },
  { word: 'subhadra yojana cash transfer', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.94 },
  { word: 'ration card e-kyc mandatory link', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.94 },
  { word: 'ayushman bharat card penalty', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.92 },
  { word: 'fastag balance block update', category: 'UTILITY_BILL', language: 'English', severity: 0.90 },
  { word: 'lpg gas subsidy pending claim', category: 'GOVERNMENT_SCHEME', language: 'Hinglish', severity: 0.92 },

  // 13. Crypto & Ponzi Schemes
  { word: 'crypto mining arbitrage bot', category: 'CRYPTO_PONZI', language: 'English', severity: 0.95 },
  { word: 'usdt double investment in 24 hours', category: 'CRYPTO_PONZI', language: 'English', severity: 0.99 },
  { word: 'daily return 50 percent guaranteed', category: 'CRYPTO_PONZI', language: 'English', severity: 0.99 },
  { word: 'forex trading mentor telegram', category: 'CRYPTO_PONZI', language: 'English', severity: 0.92 },
  { word: 'binance futures signal vip', category: 'CRYPTO_PONZI', language: 'English', severity: 0.90 },

  // 14. Regional Vernacular Scams (Tamil, Telugu, Bengali, Kannada, Marathi)
  { word: 'vangi kanaku mudapadum', category: 'VERNACULAR_REGIONAL', language: 'Tamil', severity: 0.98 },
  { word: 'panayam seiya', category: 'VERNACULAR_REGIONAL', language: 'Tamil', severity: 0.85 },
  { word: 'meethi panam', category: 'VERNACULAR_REGIONAL', language: 'Tamil', severity: 0.85 },
  { word: 'mee account block aindi', category: 'VERNACULAR_REGIONAL', language: 'Telugu', severity: 0.98 },
  { word: 'current bill kattandi', category: 'VERNACULAR_REGIONAL', language: 'Telugu', severity: 0.92 },
  { word: 'ventane update cheyandi', category: 'VERNACULAR_REGIONAL', language: 'Telugu', severity: 0.95 },
  { word: 'apnar bank account bondho', category: 'VERNACULAR_REGIONAL', language: 'Bengali', severity: 0.98 },
  { word: 'biddut connection kete deoa hobe', category: 'VERNACULAR_REGIONAL', language: 'Bengali', severity: 0.98 },
  { word: 'lottery prize jitechen', category: 'VERNACULAR_REGIONAL', language: 'Bengali', severity: 0.95 },
  { word: 'nimma khate block agide', category: 'VERNACULAR_REGIONAL', language: 'Kannada', severity: 0.98 },
  { word: 'tappade kyc update madi', category: 'VERNACULAR_REGIONAL', language: 'Kannada', severity: 0.95 },
  { word: 'tumche bank khate band hoil', category: 'VERNACULAR_REGIONAL', language: 'Marathi', severity: 0.98 },
  { word: 'bijli bill bhara lagech', category: 'VERNACULAR_REGIONAL', language: 'Marathi', severity: 0.95 },
  { word: 'tamaru bank account bandh thashe', category: 'VERNACULAR_REGIONAL', language: 'Gujarati', severity: 0.98 }
];

module.exports = {
  SEED_SCAM_WORDS
};
